# Generated by Django 4.1.3 on 2022-11-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/% Y/% m/% d/')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='remaining_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
